// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("splunklog")
	ScopeName = "splunklog_receiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
